title: Topics in machine learning.
email: mohsen.kiskani@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This page is dedicated to some interesting ideas in statistics and machine learning.
  I will try to scratch the surface about some interesting ideas. Mainly for my own benefit
  and access but maybe helpful for others too.
baseurl: "" # the subpath of your site, e.g. /blog
url: "kiskani.github.io" # the base hostname & protocol for your site
github_username:  kiskani
